<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class DetailPenyewaan_model extends CI_Model
{

    public $table = 'detail_penyewaan';
    public $id = 'id_sewa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where('detail_penyewaan.id_sewa', $id);
		$this->db->join('penyewaan', 'penyewaan.id_sewa = detail_penyewaan.id_sewa');
		$this->db->join('penyewa', 'penyewa.id_penyewa = penyewaan.id_penyewa');
		$this->db->join('movie', 'detail_penyewaan.id_movie = movie.id_movie');
        return $this->db->get($this->table);
		//$hasil = $this->db->get('detail_penyewaan');
		//return $hasil;
    }
	
	function get_id_movie($id_sewa)
	{
		$this->db->select('id_movie');
		//$this->db->from('movie');
		$this->db->where($this->id, $id_sewa);
        $hasil = $this->db->get($this->table);
		return $hasil;
	}
	
	function get_judul_movie($id_sewa)
	{
		$this->db->select('detail_penyewaan.id_movie');
		//$this->db->from('movie');
		$this->db->join('movie', 'detail_penyewaan.id_movie = movie.id_movie');
		$this->db->where($this->id, $id_sewa);
        $hasil = $this->db->get($this->table);
		return $hasil;
	}
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_detail', $q);
	$this->db->or_like('id_sewa', $q);
	$this->db->or_like('id_movie', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_detail', $q);
	$this->db->or_like('id_sewa', $q);
	$this->db->or_like('id_movie', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->join('penyewaan', 'penyewaan.id_sewa = detail_penyewaan.id_sewa');
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert('detail_penyewaan', $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Penyewaan_model.php */
/* Location: ./application/models/Penyewaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-06 16:19:21 */
/* http://harviacode.com */