<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Movie_model extends CI_Model
{

    public $table = 'movie';
    public $id = 'id_movie';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
		$this->db->join('kategori', 'movie.id_kategori = kategori.id_kategori');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_movie', $q);
	$this->db->or_like('judul', $q);
	$this->db->or_like('harga_sewa', $q);
	$this->db->or_like('stok', $q);
	$this->db->or_like('sinopsis', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_movie', $q);
		$this->db->or_like('judul', $q);
		$this->db->or_like('harga_sewa', $q);
		$this->db->or_like('stok', $q);
		$this->db->or_like('sinopsis', $q);
		$this->db->or_like('movie.id_kategori', $q);
		$this->db->limit($limit, $start);
		$this->db->join('kategori', 'movie.id_kategori = kategori.id_kategori');
        return $this->db->get($this->table)->result();
    }
	
	function get_data($q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_movie', $q);
		$this->db->or_like('judul', $q);
		$this->db->or_like('harga_sewa', $q);
		$this->db->or_like('stok', $q);
		$this->db->or_like('sinopsis', $q);
		$this->db->or_like('movie.id_kategori', $q);
		$this->db->join('kategori', 'movie.id_kategori = kategori.id_kategori');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
	
	// cek stok
    function cek_stok($id)
    {
        $this->db->select('stok');
		//$this->db->from('movie');
		$this->db->where($this->id, $id);
        $hasil = $this->db->get($this->table);
		return $hasil;
    }
	
	// cek harga
    function cek_harga($id)
    {
        $this->db->select('harga_sewa');
		//$this->db->from('movie');
		$this->db->where($this->id, $id);
        $hasil = $this->db->get($this->table);
		return $hasil;
    }
	
	// update stok
    function update_stok($id, $stok)
    {
        $data['stok'] = $stok;
		$this->db->where($this->id, $id);
		$this->db->update('movie', $data);
		/* $this->db->where($this->id, $id);
		$this->db->set('stok',0);
		$this->db->insert('movie'); */
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Movie_model.php */
/* Location: ./application/models/Movie_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-06 16:18:22 */
/* http://harviacode.com */